### ISSUE TITLE
.as extension instead of .ts

### ISSUE THREAD

**Issue by munrocket** [aspkg/cli#1]
Package managers is very useful! However AssemblyScript not support mixing two extensions (.ts and .as), so I am encouraging you to use .as in this package manager, because after that you can use it with TypeScript in one folder. It is better for AssemblyScript to use your own extension (for linting, plugins etc.)

**Comment by romdotdog** [comment]
Please file an issue in [the main AssemblyScript repository](https://github.com/AssemblyScript/assemblyscript) if you would like to see this implemented.
